export BUILT_PRODUCTS_DIR="/Users/scott/iOS/cycoredata/Example/Build/Products/Debug-iphoneos"
export CURRENT_ARCH="arm64"
export OBJECT_FILE_DIR_normal="/Users/scott/iOS/cycoredata/Example/Build/Intermediates/CYCoreData.build/Debug-iphoneos/CYCoreData.build/Objects-normal"
export OBJROOT="/Users/scott/iOS/cycoredata/Example/Build/Intermediates"
export SRCROOT="/Users/scott/iOS/cycoredata/Example"
